# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

puts "seed starting"

#Job Categories
JobCategory.delete_all
JobCategory.create(category: 'Air Con Servicing')
JobCategory.create(category: 'Air Conditioner Installation')
JobCategory.create(category: 'Air Conditioning Cleaning')
JobCategory.create(category: 'Air Conditioning Repair')
JobCategory.create(category: 'Air Conditioning Technicians')
JobCategory.create(category: 'Air Duct Cleaners')
JobCategory.create(category: 'Aluminium Doors')
JobCategory.create(category: 'Aluminium Fencing')
JobCategory.create(category: 'Aluminium Scaffolding')
JobCategory.create(category: 'Aluminium Windows')
JobCategory.create(category: 'Antenna Installation')
JobCategory.create(category: 'Antenna Repair')
JobCategory.create(category: 'Appliance Installation')
JobCategory.create(category: 'Arborist')
JobCategory.create(category: 'Architraves')
JobCategory.create(category: 'Asbestos Identification')
JobCategory.create(category: 'Asbestos Removal')
JobCategory.create(category: 'Asphalt Driveways')
JobCategory.create(category: 'Automatic Gates')
JobCategory.create(category: 'Awning Windows')
JobCategory.create(category: 'Awnings')
JobCategory.create(category: 'Balcony Waterproofing')
JobCategory.create(category: 'Balustrading')
JobCategory.create(category: 'Bamboo Fencing')
JobCategory.create(category: 'Bath Resurfacing')
JobCategory.create(category: 'Bathroom Ceilings')
JobCategory.create(category: 'Bathroom Resurfacing')
JobCategory.create(category: 'Bathroom Tap Installation')
JobCategory.create(category: 'Bathroom Tiling')
JobCategory.create(category: 'Bathroom Waterproofing')
JobCategory.create(category: 'Bees')
JobCategory.create(category: 'Birds')
JobCategory.create(category: 'Blind Cleaning')
JobCategory.create(category: 'Blocked Toilet')
JobCategory.create(category: 'Brick Fence')
JobCategory.create(category: 'Bricklayers')
JobCategory.create(category: 'Broken Sink Repair And Replacement')
JobCategory.create(category: 'Built In Wardrobes')
JobCategory.create(category: 'Cabinetmaking')
JobCategory.create(category: 'Carpenters')
JobCategory.create(category: 'Carpet Cleaning')
JobCategory.create(category: 'Carpet Installation')
JobCategory.create(category: 'Carpet Removal')
JobCategory.create(category: 'Carpet Restretching')
JobCategory.create(category: 'Carpet Water Extraction')
JobCategory.create(category: 'Ceiling Insulation')
JobCategory.create(category: 'Central Heating')
JobCategory.create(category: 'Clogged And Block Drain')
JobCategory.create(category: 'Colorbond Fencing')
JobCategory.create(category: 'Colorbond Roofing')
JobCategory.create(category: 'Concrete Driveway')
JobCategory.create(category: 'Concreters')
JobCategory.create(category: 'Decking')
JobCategory.create(category: 'Dishwasher Installation')
JobCategory.create(category: 'Dishwasher Repair')
JobCategory.create(category: 'Down Lighting')
JobCategory.create(category: 'Drain Repairs')
JobCategory.create(category: 'Driveway Paving')
JobCategory.create(category: 'Duct Installation')
JobCategory.create(category: 'Ducted Air Conditioning')
JobCategory.create(category: 'Ducted Gas Heating')
JobCategory.create(category: 'Electric Heaters')
JobCategory.create(category: 'Electric Hot Water Systems')
JobCategory.create(category: 'Electric Ovens')
JobCategory.create(category: 'Electrical Repairs')
JobCategory.create(category: 'Emergency Locksmith')
JobCategory.create(category: 'Emergency Plumber')
JobCategory.create(category: 'Exhaust Fans')
JobCategory.create(category: 'Exterior Window Cleaning')
JobCategory.create(category: 'Exterminators')
JobCategory.create(category: 'Fence Installation')
JobCategory.create(category: 'Fence Painting')
JobCategory.create(category: 'Fence Repairs')
JobCategory.create(category: 'Fix Leaking Tap')
JobCategory.create(category: 'Fix Leaking Toilet')
JobCategory.create(category: 'Floor Sanding')
JobCategory.create(category: 'Floor Tiling')
JobCategory.create(category: 'Floorboards')
JobCategory.create(category: 'Fly Screens')
JobCategory.create(category: 'Garage Door Repair')
JobCategory.create(category: 'Garage Roller Door')
JobCategory.create(category: 'Gardeners')
JobCategory.create(category: 'Gas Fitting')
JobCategory.create(category: 'Gas Heaters And Fireplaces')
JobCategory.create(category: 'Gas Hot Water Systems')
JobCategory.create(category: 'Gate Repair')
JobCategory.create(category: 'Grout Cleaning')
JobCategory.create(category: 'Gutter Cleaning')
JobCategory.create(category: 'Gutter Repairs')
JobCategory.create(category: 'Handyman Services')
JobCategory.create(category: 'Hot Water Repairs')
JobCategory.create(category: 'Hydronic Heating')
JobCategory.create(category: 'Insulation')
JobCategory.create(category: 'Intercom')
JobCategory.create(category: 'Interior Painting')
JobCategory.create(category: 'Laminate Flooring')
JobCategory.create(category: 'Landscaping And Gardening')
JobCategory.create(category: 'Lighting Repairs')
JobCategory.create(category: 'Locksmiths')
JobCategory.create(category: 'Mould Removal')
JobCategory.create(category: 'Oven Repair')
JobCategory.create(category: 'Painters')
JobCategory.create(category: 'Parquetry Flooring')
JobCategory.create(category: 'Paving')
JobCategory.create(category: 'Pest Control')
JobCategory.create(category: 'Phone Line Installation')
JobCategory.create(category: 'Phone Line Repairs')
JobCategory.create(category: 'Plasterers')
JobCategory.create(category: 'Pool Cleaners')
JobCategory.create(category: 'Pool Filters')
JobCategory.create(category: 'Pool Heating')
JobCategory.create(category: 'Pool Leak Repair')
JobCategory.create(category: 'Pool Maintenance')
JobCategory.create(category: 'Possums')
JobCategory.create(category: 'Rewiring')
JobCategory.create(category: 'Rising Damp')
JobCategory.create(category: 'Roller Blinds')
JobCategory.create(category: 'Roller Doors And Shutters')
JobCategory.create(category: 'Roof Repairs')
JobCategory.create(category: 'Roofers')
JobCategory.create(category: 'Satellite Dish Installation And Repair')
JobCategory.create(category: 'Screen Door')
JobCategory.create(category: 'Security Alarm Systems')
JobCategory.create(category: 'Shade Sail Awnings')
JobCategory.create(category: 'Shower Screens')
JobCategory.create(category: 'Shower Sealing')
JobCategory.create(category: 'Skylight Repairs')
JobCategory.create(category: 'Sliding Doors')
JobCategory.create(category: 'Smoke Alarm Installation And Replacement')
JobCategory.create(category: 'Stove Repairs')
JobCategory.create(category: 'Tv Aerial Repair')
JobCategory.create(category: 'Venetian Blinds')
JobCategory.create(category: 'Vertical Blinds')
JobCategory.create(category: 'Vinyl Flooring')

#Job Statuses
JobStatus.delete_all
JobStatus.create(status: 'Created')
JobStatus.create(status: 'Accepted')
JobStatus.create(status: 'Completed')
JobStatus.create(status: 'Paid')

puts "seed complete"
